### ISSUE TITLE
Can I take over this repo / publish to NPM

### ISSUE THREAD

**Issue by keithwhor** [upspawn/wavtools#1]
Hey folks, just took the time to publish this on my account:

https://github.com/keithwhor/wavetools

Also to NPM:
https://www.npmjs.com/package/wavetools

Can I take the original NPM name back and we use my repo as source of truth? Thanks!

**Comment by alexerm** [comment]
Hi @keithwhor, happy to let you take over the NPM package name! 👍 It is great you have decided to make proper NPM package out of it. Since there’s no transfer option, I can add 'keithwhor' as a maintainer. From there, you can manage it as you prefer. Let me know if that works!

**Comment by keithwhor** [comment]
Hey @alexerm -- thank you so much!

https://github.com/keithwhor/wavtools

The README isn't that comprehensive yet; if you want to commit some of what's here that'd be great! Happy to add you as a maintainer as well to the GH repo.

**Comment by alexerm** [comment]
I would love to contribute, especially the docs!

**Comment by keithwhor** [comment]
Added you as a collaborator! Feel free to make updates.

I prefer not to have commits to main automatically publish NPM repos; I like manual control there because I've had some oopsies before. But other than that -- if you have ideas feel free to drop 'em! Maybe we should make a Discord or something.

**Comment by alexerm** [comment]
Thanks! I think using tagging along with a manual GitHub action for publishing could be a solid approach to keep control over updates.

I'm also open to setting up a Discord. Additionally, I'll deprecate https://github.com/upspawn/wavtools later today to streamline everything under your repo.

I’ve been working on a React UI toolkit that integrates with OpenAI’s Realtime API using your library, and I've run into a few inconsistencies with sound processing. I’ll dig into those as I contribute here and, if I can pinpoint the issue, I’d be happy to submit a PR to address them.

Looking forward to collaborating!
